// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        kotlin_version = '2.3.10'
    }
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath libs.gradle
        classpath libs.kotlin.gradle.plugin
        classpath libs.play.services.oss.licenses.plugin
    }
}
tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
}

ext {
    toolsVersion = properties.get('TOOLS_VERSION', '35.0.0')
    compileApi = properties.get('COMPILE_API', 35)
    targetApi = properties.get('TARGET_API', 28)
    minApi = properties.get('MIN_API', 23)
}
